version: "3"
services:
  backend:
    build:
      context: ../../backend
      dockerfile: $PWD/backend/Dockerfile
    ports:
      - "8080:3000"
    env_file:
      - ../../backend/src/.development.env
    restart: "always"
    command: [ "run", "start:dev" ]
    volumes:
      - ../../backend:/app
    networks:
      - flloport
    links:
      - database
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - 5432
    networks:
      - flloport
    env_file:
      - ../../backend/src/.development.env

networks:
  flloport: