version: "3"
services:
  backend:
    build:
      context: ../../backend
      dockerfile: $PWD/backend/Dockerfile
    ports:
      - "8080:3000"
    env_file:
      - ../../backend/src/.development.env
    restart: "always"
    command: [ "run", "start:dev" ]
    volumes:
      - ../../backend:/app
    networks:
      - flloport
networks:
  flloport: